########################
### Avenue  Dataset ###
#######################

GPUS: (0,1,2,3,4,5,6,7,)
PRINT_FREQ: 30

DATA:
  BATCH_SIZE: 32               # 7 # 4
  IMG_SIZE: [256, 256]
  DATASET: 'avenue'
  FRAME_STEP: 2
  MIN_FRAMES: 300
  NUM_WORKERS: 2

MODEL:
  NAME: HSTforU
  PRETRAINED: '../../datasets/seg_weights/pvt_v2_b2.pth'

TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 10
  BASE_LR: 5e-4
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
  LR_SCHEDULER:
    NAME: 'cosine'
    DECAY_RATE: 0.5
  OPTIMIZER:
    NAME: 'adamw'

##############################################################

##############################################################